# Generated by Django 4.0.5 on 2022-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about_book',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
